project:
  type: website
  output-dir: docs

website:
  title: "estefania mitre"
  navbar:
    right:
      - index.qmd
      - resume.qmd
      - videoportfolio.qmd
      - fotos.qmd
      - socialportfolio.qmd
format:
  html:
    theme: sketchy
    css: styles.css
resources:
  - CNAME



