project:
  type: website
  output-dir: docs

website:
  title: "estefania mitre"
  page-navigation: true
  navbar:
    background: light
    right:
      - index.qmd
      # - social-media-impact.qmd
      - sidebar:portfolios
      
  sidebar:
    - id: portfolios
      tile: "Portfolio"
      style: "docked"
      collapse-level: 2
      contents:
        - portfolio-video.qmd
        - portfolio-multimedia.qmd
        - portfolio-online.qmd

format:
  html:
    theme: lux
    css: styles.css
resources:
  - CNAME



